service: acceptessa-checklist-api
provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ssm:GetParameter
      Resource:
        - Fn::Join: [ ":", ["arn:aws:ssm", { Ref: AWS::Region }, { Ref: AWS::AccountId }, "parameter/twitter_oauth/jwt_token"]]
    - Effect: Allow
      Action:
        - dynamodb:GetItem
      Resource:
        - Fn::Join: [ ":", ["arn:aws:dynamodb", { Ref: AWS::Region }, { Ref: AWS::AccountId }, "table/twitter_oauth"]]
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:BatchGetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - Fn::Join: [ ":", ["arn:aws:dynamodb", { Ref: AWS::Region }, { Ref: AWS::AccountId }, "table/tessa_favorite"]]
        - Fn::Join: [ ":", ["arn:aws:dynamodb", { Ref: AWS::Region }, { Ref: AWS::AccountId }, "table/tessa_favorite/index/*"]]
        - Fn::Join: [ ":", ["arn:aws:dynamodb", { Ref: AWS::Region }, { Ref: AWS::AccountId }, "table/tessa_config"]]

functions:
  endpoint:
    handler: handler.endpoint
    events:
      - http:
          path: endpoint
          method: post
          cors: true

resources:
  Description: Acceptessa checklist api
  Resources:
    FavoriteTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: tessa_favorite
        AttributeDefinitions:
          - { AttributeName: member_id,     AttributeType: S }
          - { AttributeName: circle_id,     AttributeType: S }
          - { AttributeName: exhibition_id, AttributeType: S }
        KeySchema:
          - { AttributeName: member_id,     KeyType: HASH }
          - { AttributeName: circle_id,     KeyType: RANGE }
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: tessa_favorite_gsi1
            KeySchema:
              - { AttributeName: member_id,     KeyType: HASH }
              - { AttributeName: exhibition_id, KeyType: RANGE }
            Projection:
              ProjectionType: KEYS_ONLY
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1

    ConfigTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: tessa_config
        AttributeDefinitions:
          - { AttributeName: member_id,     AttributeType: S }
          - { AttributeName: exhibition_id, AttributeType: S }
        KeySchema:
          - { AttributeName: member_id,     KeyType: HASH }
          - { AttributeName: exhibition_id, KeyType: RANGE }
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    WCUAlarm:
      Type: AWS::CloudWatch::Alarm
      Properties:
        AlarmName: "acceptessa-checklist-tessa_favorite-dynamodb-wcu"
        AlarmDescription: "DynamoDB WCU alarm for acceptessa-checklist"
        ComparisonOperator: GreaterThanOrEqualToThreshold
        Dimensions:
          - { Name: TableName, Value: { Ref: FavoriteTable } }
        EvaluationPeriods: 1
        MetricName: ConsumedWriteCapacityUnits
        Namespace: AWS/DynamoDB
        Period: 60
        Statistic: Maximum
        Threshold: 60
        TreatMissingData: notBreaching
        AlarmActions:
          - Fn::Join: [ ":", ["arn:aws:sns", { Ref: AWS::Region }, { Ref: AWS::AccountId }, "aws-slack-notifier"]]
        OKActions:
          - Fn::Join: [ ":", ["arn:aws:sns", { Ref: AWS::Region }, { Ref: AWS::AccountId }, "aws-slack-notifier"]]

    RCUAlarm:
      Type: AWS::CloudWatch::Alarm
      Properties:
        AlarmName: "acceptessa-checklist-tessa_favorite-dynamodb-rcu"
        AlarmDescription: "DynamoDB RCU alarm for acceptessa-checklist"
        ComparisonOperator: GreaterThanOrEqualToThreshold
        Dimensions:
          - { Name: TableName, Value: { Ref: FavoriteTable } }
        EvaluationPeriods: 1
        MetricName: ConsumedReadCapacityUnits
        Namespace: AWS/DynamoDB
        Period: 60
        Statistic: Maximum
        Threshold: 60
        TreatMissingData: notBreaching
        AlarmActions:
          - Fn::Join: [ ":", ["arn:aws:sns", { Ref: AWS::Region }, { Ref: AWS::AccountId }, "aws-slack-notifier"]]
        OKActions:
          - Fn::Join: [ ":", ["arn:aws:sns", { Ref: AWS::Region }, { Ref: AWS::AccountId }, "aws-slack-notifier"]]