service: acceptessa-checklist-api
provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: ap-northeast-1
  deploymentBucket: serverless-upload-ap-northeast-1
  versionFunctions: false
  iamRoleStatements:
    - Effect: Allow
      Action: [ssm:GetParameter]
      Resource:
        - Fn::Join: [ ":", ["arn:aws:ssm", { Ref: AWS::Region }, { Ref: AWS::AccountId }, "parameter/gomitter/twitter_consumer_key"]]
        - Fn::Join: [ ":", ["arn:aws:ssm", { Ref: AWS::Region }, { Ref: AWS::AccountId }, "parameter/gomitter/twitter_consumer_secret"]]
        - Fn::Join: [ ":", ["arn:aws:ssm", { Ref: AWS::Region }, { Ref: AWS::AccountId }, "parameter/gomitter/jwt_token"]]
    - Effect: Allow
      Action: [dynamodb:GetItem, dynamodb:PutItem, dynamodb:DeleteItem]
      Resource:
        - Fn::Join: [ ":", ["arn:aws:dynamodb", { Ref: AWS::Region }, { Ref: AWS::AccountId }, "table/tessa_session"]]
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:BatchGetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - Fn::Join: [ ":", ["arn:aws:dynamodb", { Ref: AWS::Region }, { Ref: AWS::AccountId }, "table/tessa_favorite"]]
        - Fn::Join: [ ":", ["arn:aws:dynamodb", { Ref: AWS::Region }, { Ref: AWS::AccountId }, "table/tessa_favorite/index/*"]]
        - Fn::Join: [ ":", ["arn:aws:dynamodb", { Ref: AWS::Region }, { Ref: AWS::AccountId }, "table/tessa_config"]]

functions:
  endpoint:
    handler: handler.endpoint
    events:
      - http:
          path: /
          method: post
          cors: true
  public:
    handler: handler.public
    events:
      - http:
          path: /public/{eid}/
          method: get
          cors: true
  auth:
    handler: handler.auth
    events: [{ http: { path: "/auth/{action}", method: get, cors: true } }]

resources:
  Description: Acceptessa checklist api
  Resources:
    ## tables
    FavoriteTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: tessa_favorite
        AttributeDefinitions:
          - { AttributeName: member_id,     AttributeType: S }
          - { AttributeName: circle_id,     AttributeType: S }
          - { AttributeName: exhibition_id, AttributeType: S }
        KeySchema:
          - { AttributeName: member_id,     KeyType: HASH }
          - { AttributeName: circle_id,     KeyType: RANGE }
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        GlobalSecondaryIndexes:
          - IndexName: tessa_favorite_gsi
            KeySchema:
              - { AttributeName: member_id,     KeyType: HASH }
              - { AttributeName: exhibition_id, KeyType: RANGE }
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1

    ConfigTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: tessa_config
        AttributeDefinitions:
          - { AttributeName: member_id,     AttributeType: S }
          - { AttributeName: exhibition_id, AttributeType: S }
        KeySchema:
          - { AttributeName: member_id,     KeyType: HASH }
          - { AttributeName: exhibition_id, KeyType: RANGE }
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    SessionTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: tessa_session
        AttributeDefinitions:
          - { AttributeName: uid, AttributeType: S }
        KeySchema:
          - { AttributeName: uid, KeyType: HASH }
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true

    ## alarms
    WCUAlarm:
      Type: AWS::CloudWatch::Alarm
      Properties:
        AlarmName: "acceptessa-checklist-tessa_favorite-dynamodb-wcu"
        AlarmDescription: "DynamoDB WCU alarm for acceptessa-checklist"
        ComparisonOperator: GreaterThanOrEqualToThreshold
        Dimensions:
          - { Name: TableName, Value: { Ref: FavoriteTable } }
        EvaluationPeriods: 1
        MetricName: ConsumedWriteCapacityUnits
        Namespace: AWS/DynamoDB
        Period: 60
        Statistic: Maximum
        Threshold: 60
        TreatMissingData: notBreaching
        AlarmActions:
          - Fn::Join: [ ":", ["arn:aws:sns", { Ref: AWS::Region }, { Ref: AWS::AccountId }, "aws-slack-notifier"]]
        OKActions:
          - Fn::Join: [ ":", ["arn:aws:sns", { Ref: AWS::Region }, { Ref: AWS::AccountId }, "aws-slack-notifier"]]

    RCUAlarm:
      Type: AWS::CloudWatch::Alarm
      Properties:
        AlarmName: "acceptessa-checklist-tessa_favorite-dynamodb-rcu"
        AlarmDescription: "DynamoDB RCU alarm for acceptessa-checklist"
        ComparisonOperator: GreaterThanOrEqualToThreshold
        Dimensions:
          - { Name: TableName, Value: { Ref: FavoriteTable } }
        EvaluationPeriods: 1
        MetricName: ConsumedReadCapacityUnits
        Namespace: AWS/DynamoDB
        Period: 60
        Statistic: Maximum
        Threshold: 60
        TreatMissingData: notBreaching
        AlarmActions:
          - Fn::Join: [ ":", ["arn:aws:sns", { Ref: AWS::Region }, { Ref: AWS::AccountId }, "aws-slack-notifier"]]
        OKActions:
          - Fn::Join: [ ":", ["arn:aws:sns", { Ref: AWS::Region }, { Ref: AWS::AccountId }, "aws-slack-notifier"]]

    ## domain setting
    Domain:
      Type: AWS::ApiGateway::DomainName
      Properties:
        CertificateArn: "${ssm:/tessa_checklist/acm_cert_arn~true}"
        DomainName: "api.familiar-life.info"

    Mapping:
      Type: AWS::ApiGateway::BasePathMapping
      Properties:
        DomainName: { Ref: Domain }
        RestApiId:  { Ref: ApiGatewayRestApi }
        Stage: dev

    RecordSetOfAPI:
      Type: AWS::Route53::RecordSet
      Properties:
        Name: "api.familiar-life.info"
        Type: A
        HostedZoneName: "familiar-life.info."
        AliasTarget:
          DNSName: { Fn::GetAtt: [Domain, DistributionDomainName] }
          HostedZoneId: Z2FDTNDATAQYW2