service: acceptessa-checklist
variablesResolutionMode: 20210326

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-northeast-1
  deploymentBucket: serverless-upload-ap-northeast-1
  versionFunctions: false

  iam:
    role:
      statements:
        - Effect: Allow
          Action: [dynamodb:GetItem, dynamodb:PutItem, dynamodb:DeleteItem]
          Resource:
            - Fn::Join: [ ":", ["arn:aws:dynamodb", { Ref: AWS::Region }, { Ref: AWS::AccountId }, "table/tessa_session"]]
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:GetItem
            - dynamodb:BatchGetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::Join: [ ":", ["arn:aws:dynamodb", { Ref: AWS::Region }, { Ref: AWS::AccountId }, "table/tessa_favorite"]]
            - Fn::Join: [ ":", ["arn:aws:dynamodb", { Ref: AWS::Region }, { Ref: AWS::AccountId }, "table/tessa_favorite/index/*"]]
            - Fn::Join: [ ":", ["arn:aws:dynamodb", { Ref: AWS::Region }, { Ref: AWS::AccountId }, "table/tessa_config"]]
        - Effect: Allow
          Action: [dynamodb:GetItem, dynamodb:UpdateItem]
          Resource:
            - Fn::Join: [ ":", ["arn:aws:dynamodb", { Ref: AWS::Region }, { Ref: AWS::AccountId }, "table/tessa_favorite_count"]]
        - Effect: Allow
          Action: [s3:PutObject]
          Resource:
            - Fn::Join: [ "", [{ Fn::GetAtt: [ExportBucket, Arn]}, "/*"]]

functions:
  endpoint:
    handler: handler.endpoint
    description: tessa checklist application
    events: [{ http: { path: "/api/endpoint", method: post, cors: true } }]
    environment:
      S3BUCKET_PUBLIC_URL: { Fn::GetAtt: [ExportBucket, DomainName] }
      SSM_KEY_JWT_SECRET:  "${ssm:/tessa_checklist/jwt_secret}"

  public:
    handler: handler.public
    description: tessa checklist public endpoint
    events: [{ http: { path: "/api/public/{eid}/", method: get, cors: true } }]

  auth:
    handler: handler.auth
    description: tessa checklist authentication
    events: [{ http: { path: "/api/auth/{action}", method: get, cors: true } }]
    environment:
      SERVE_HOST:              "checklist.familiar-life.info"
      SSM_KEY_CONSUMER_KEY:    "${ssm:/tessa_checklist/twitter_consumer_key}"
      SSM_KEY_CONSUMER_SECRET: "${ssm:/tessa_checklist/twitter_consumer_secret}"
      SSM_KEY_JWT_SECRET:      "${ssm:/tessa_checklist/jwt_secret}"

  stream:
    handler: handler.stream
    events:
      - stream:
          type: dynamodb
          arn: { Fn::GetAtt: [FavoriteTable, StreamArn] }

resources:
  Description: Acceptessa checklist api
  Resources:
    ## override
    IamRoleLambdaExecution:
      Type: AWS::IAM::Role
      Properties:
        RoleName: "${self:service}"
    EndpointLogGroup:
      Type: AWS::Logs::LogGroup
      Properties: { RetentionInDays: 7 }
    PublicLogGroup:
      Type: AWS::Logs::LogGroup
      Properties: { RetentionInDays: 7 }
    AuthLogGroup:
      Type: AWS::Logs::LogGroup
      Properties: { RetentionInDays: 7 }
    StreamLogGroup:
      Type: AWS::Logs::LogGroup
      Properties: { RetentionInDays: 7 }

    ## bucket and policy
    Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: "${self:service}"

    BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: { Ref: Bucket }
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action: s3:GetObject
              Principal:
                AWS: !Sub arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOriginAccessIdentity}
              Resource:
                Fn::Join: [ "/", [ !GetAtt [ Bucket, Arn ], "*" ] ]

    ExportBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: "${self:service}-export"
        WebsiteConfiguration:
          ErrorDocument: error.html
          IndexDocument: index.html

    ConfigBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: "${self:service}-config"

    ConfigBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: { Ref: ConfigBucket }
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action: s3:GetObject
              Principal:
                AWS: !Sub arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOriginAccessIdentity2}
              Resource:
                Fn::Join: [ "/", [ !GetAtt [ ConfigBucket, Arn ], "*" ] ]

    ExportBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: { Ref: ExportBucket }
        PolicyDocument:
          Statement:
            - Effect: Allow
              Action: ["s3:GetObject"]
              Principal: "*"
              Resource:
                Fn::Join: [ "", [ !GetAtt [ExportBucket, Arn], "/*" ]]

    ## tables
    FavoriteTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: tessa_favorite
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - { AttributeName: member_id,     AttributeType: S }
          - { AttributeName: circle_id,     AttributeType: S }
          - { AttributeName: exhibition_id, AttributeType: S }
        KeySchema:
          - { AttributeName: member_id,     KeyType: HASH }
          - { AttributeName: circle_id,     KeyType: RANGE }
        GlobalSecondaryIndexes:
          - IndexName: tessa_favorite_gsi
            KeySchema:
              - { AttributeName: member_id,     KeyType: HASH }
              - { AttributeName: exhibition_id, KeyType: RANGE }
            Projection:
              ProjectionType: ALL
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES

    ConfigTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: tessa_config
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - { AttributeName: member_id,     AttributeType: S }
          - { AttributeName: exhibition_id, AttributeType: S }
        KeySchema:
          - { AttributeName: member_id,     KeyType: HASH }
          - { AttributeName: exhibition_id, KeyType: RANGE }

    SessionTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: tessa_session
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - { AttributeName: uid, AttributeType: S }
        KeySchema:
          - { AttributeName: uid, KeyType: HASH }
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true

    CountTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: tessa_favorite_count
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - { AttributeName: circle_id, AttributeType: S }
        KeySchema:
          - { AttributeName: circle_id, KeyType: HASH }

    ## static file domain setting
    Cloudfront:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Comment: acceptessa checklist
          Aliases: ["checklist.familiar-life.info"]
          HttpVersion: http2
          ViewerCertificate:
            AcmCertificateArn: "${ssm:/tessa_checklist/acm_cert_arn}"
            SslSupportMethod: sni-only
          DefaultRootObject: index.html
          DefaultCacheBehavior:
            TargetOriginId: s3static
            ViewerProtocolPolicy: redirect-to-https
            ForwardedValues:
              QueryString: true
              Headers: ["Origin"]
            MinTTL: 43200 ## 12 hour
            MaxTTL: 43200
            DefaultTTL: 43200
            LambdaFunctionAssociations:
              - EventType: viewer-request
                LambdaFunctionARN: !Sub "arn:aws:lambda:us-east-1:${AWS::AccountId}:function:acceptessa-checklist-ogp-dev-ogp:16"
          CacheBehaviors:
            - PathPattern: /api/*
              AllowedMethods: [GET, HEAD, OPTIONS, PUT, PATCH, POST, DELETE]
              CachedMethods: [GET, HEAD]
              TargetOriginId: api
              ViewerProtocolPolicy: redirect-to-https
              ForwardedValues:
                Cookies:
                  Forward: whitelist
                  WhitelistedNames: ['sessid']
                QueryString: true
                Headers: ["Origin"]
              MinTTL: 0
              MaxTTL: 0
              DefaultTTL: 0
            - PathPattern: /config/*
              AllowedMethods: [GET, HEAD, OPTIONS, PUT, PATCH, POST, DELETE]
              CachedMethods: [GET, HEAD]
              TargetOriginId: s3config
              ViewerProtocolPolicy: redirect-to-https
              ForwardedValues:
                QueryString: true
                Headers: ["Origin"]
              MinTTL: 43200
              MaxTTL: 43200
              DefaultTTL: 43200
          Enabled: true
          Origins:
            - Id: s3static
              DomainName: !GetAtt Bucket.DomainName
              S3OriginConfig:
                OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}
            - Id: s3config
              DomainName: !GetAtt ConfigBucket.DomainName
              S3OriginConfig:
                OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity2}
            - Id: api
              DomainName: { Fn::Join: ["", [{ Ref:  ApiGatewayRestApi }, ".execute-api.ap-northeast-1.amazonaws.com" ]] }
              OriginPath: /dev
              CustomOriginConfig:
                OriginProtocolPolicy: https-only
                OriginSSLProtocols: [TLSv1.1, TLSv1.2]

    CloudFrontOriginAccessIdentity:
      Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
      Properties:
        CloudFrontOriginAccessIdentityConfig:
          Comment:
            Fn::Join: [" ", [!Ref AWS::StackName, "static file"]]

    CloudFrontOriginAccessIdentity2:
      Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
      Properties:
        CloudFrontOriginAccessIdentityConfig:
          Comment:
            Fn::Join: [" ", [!Ref AWS::StackName, "config file"]]

    RecordSetOfAssets:
      Type: AWS::Route53::RecordSet
      Properties:
        Name: "checklist.familiar-life.info"
        Type: A
        HostedZoneName: "familiar-life.info."
        AliasTarget:
          DNSName: !GetAtt Cloudfront.DomainName
          HostedZoneId: Z2FDTNDATAQYW2
